// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.lvl6.proto;

public final class EventProto {
  private EventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class ChatRequestProto extends
      com.google.protobuf.GeneratedMessage {
    // Use ChatRequestProto.newBuilder() to construct.
    private ChatRequestProto() {}
    
    private static final ChatRequestProto defaultInstance = new ChatRequestProto();
    public static ChatRequestProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChatRequestProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatRequestProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatRequestProto_fieldAccessorTable;
    }
    
    // required int32 playerId = 1;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private boolean hasPlayerId;
    private int playerId_ = 0;
    public boolean hasPlayerId() { return hasPlayerId; }
    public int getPlayerId() { return playerId_; }
    
    // optional int32 event = 2;
    public static final int EVENT_FIELD_NUMBER = 2;
    private boolean hasEvent;
    private int event_ = 0;
    public boolean hasEvent() { return hasEvent; }
    public int getEvent() { return event_; }
    
    // repeated .com.lvl6.proto.UserProto recipients = 3;
    public static final int RECIPIENTS_FIELD_NUMBER = 3;
    private java.util.List<com.lvl6.proto.InfoProto.UserProto> recipients_ =
      java.util.Collections.emptyList();
    public java.util.List<com.lvl6.proto.InfoProto.UserProto> getRecipientsList() {
      return recipients_;
    }
    public int getRecipientsCount() { return recipients_.size(); }
    public com.lvl6.proto.InfoProto.UserProto getRecipients(int index) {
      return recipients_.get(index);
    }
    
    // required string message = 4;
    public static final int MESSAGE_FIELD_NUMBER = 4;
    private boolean hasMessage;
    private java.lang.String message_ = "";
    public boolean hasMessage() { return hasMessage; }
    public java.lang.String getMessage() { return message_; }
    
    public final boolean isInitialized() {
      if (!hasPlayerId) return false;
      if (!hasMessage) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasPlayerId()) {
        output.writeInt32(1, getPlayerId());
      }
      if (hasEvent()) {
        output.writeInt32(2, getEvent());
      }
      for (com.lvl6.proto.InfoProto.UserProto element : getRecipientsList()) {
        output.writeMessage(3, element);
      }
      if (hasMessage()) {
        output.writeString(4, getMessage());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasPlayerId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getPlayerId());
      }
      if (hasEvent()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getEvent());
      }
      for (com.lvl6.proto.InfoProto.UserProto element : getRecipientsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      if (hasMessage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getMessage());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.proto.EventProto.ChatRequestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.lvl6.proto.EventProto.ChatRequestProto result;
      
      // Construct using com.lvl6.proto.EventProto.ChatRequestProto.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.lvl6.proto.EventProto.ChatRequestProto();
        return builder;
      }
      
      protected com.lvl6.proto.EventProto.ChatRequestProto internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.lvl6.proto.EventProto.ChatRequestProto();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.proto.EventProto.ChatRequestProto.getDescriptor();
      }
      
      public com.lvl6.proto.EventProto.ChatRequestProto getDefaultInstanceForType() {
        return com.lvl6.proto.EventProto.ChatRequestProto.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.lvl6.proto.EventProto.ChatRequestProto build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.lvl6.proto.EventProto.ChatRequestProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.lvl6.proto.EventProto.ChatRequestProto buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.recipients_ != java.util.Collections.EMPTY_LIST) {
          result.recipients_ =
            java.util.Collections.unmodifiableList(result.recipients_);
        }
        com.lvl6.proto.EventProto.ChatRequestProto returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.proto.EventProto.ChatRequestProto) {
          return mergeFrom((com.lvl6.proto.EventProto.ChatRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.proto.EventProto.ChatRequestProto other) {
        if (other == com.lvl6.proto.EventProto.ChatRequestProto.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasEvent()) {
          setEvent(other.getEvent());
        }
        if (!other.recipients_.isEmpty()) {
          if (result.recipients_.isEmpty()) {
            result.recipients_ = new java.util.ArrayList<com.lvl6.proto.InfoProto.UserProto>();
          }
          result.recipients_.addAll(other.recipients_);
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setPlayerId(input.readInt32());
              break;
            }
            case 16: {
              setEvent(input.readInt32());
              break;
            }
            case 26: {
              com.lvl6.proto.InfoProto.UserProto.Builder subBuilder = com.lvl6.proto.InfoProto.UserProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRecipients(subBuilder.buildPartial());
              break;
            }
            case 34: {
              setMessage(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required int32 playerId = 1;
      public boolean hasPlayerId() {
        return result.hasPlayerId();
      }
      public int getPlayerId() {
        return result.getPlayerId();
      }
      public Builder setPlayerId(int value) {
        result.hasPlayerId = true;
        result.playerId_ = value;
        return this;
      }
      public Builder clearPlayerId() {
        result.hasPlayerId = false;
        result.playerId_ = 0;
        return this;
      }
      
      // optional int32 event = 2;
      public boolean hasEvent() {
        return result.hasEvent();
      }
      public int getEvent() {
        return result.getEvent();
      }
      public Builder setEvent(int value) {
        result.hasEvent = true;
        result.event_ = value;
        return this;
      }
      public Builder clearEvent() {
        result.hasEvent = false;
        result.event_ = 0;
        return this;
      }
      
      // repeated .com.lvl6.proto.UserProto recipients = 3;
      public java.util.List<com.lvl6.proto.InfoProto.UserProto> getRecipientsList() {
        return java.util.Collections.unmodifiableList(result.recipients_);
      }
      public int getRecipientsCount() {
        return result.getRecipientsCount();
      }
      public com.lvl6.proto.InfoProto.UserProto getRecipients(int index) {
        return result.getRecipients(index);
      }
      public Builder setRecipients(int index, com.lvl6.proto.InfoProto.UserProto value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.recipients_.set(index, value);
        return this;
      }
      public Builder setRecipients(int index, com.lvl6.proto.InfoProto.UserProto.Builder builderForValue) {
        result.recipients_.set(index, builderForValue.build());
        return this;
      }
      public Builder addRecipients(com.lvl6.proto.InfoProto.UserProto value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.recipients_.isEmpty()) {
          result.recipients_ = new java.util.ArrayList<com.lvl6.proto.InfoProto.UserProto>();
        }
        result.recipients_.add(value);
        return this;
      }
      public Builder addRecipients(com.lvl6.proto.InfoProto.UserProto.Builder builderForValue) {
        if (result.recipients_.isEmpty()) {
          result.recipients_ = new java.util.ArrayList<com.lvl6.proto.InfoProto.UserProto>();
        }
        result.recipients_.add(builderForValue.build());
        return this;
      }
      public Builder addAllRecipients(
          java.lang.Iterable<? extends com.lvl6.proto.InfoProto.UserProto> values) {
        if (result.recipients_.isEmpty()) {
          result.recipients_ = new java.util.ArrayList<com.lvl6.proto.InfoProto.UserProto>();
        }
        super.addAll(values, result.recipients_);
        return this;
      }
      public Builder clearRecipients() {
        result.recipients_ = java.util.Collections.emptyList();
        return this;
      }
      
      // required string message = 4;
      public boolean hasMessage() {
        return result.hasMessage();
      }
      public java.lang.String getMessage() {
        return result.getMessage();
      }
      public Builder setMessage(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessage = true;
        result.message_ = value;
        return this;
      }
      public Builder clearMessage() {
        result.hasMessage = false;
        result.message_ = getDefaultInstance().getMessage();
        return this;
      }
    }
    
    static {
      com.lvl6.proto.EventProto.getDescriptor();
    }
    
    static {
      com.lvl6.proto.EventProto.internalForceInit();
    }
  }
  
  public static final class ChatResponseProto extends
      com.google.protobuf.GeneratedMessage {
    // Use ChatResponseProto.newBuilder() to construct.
    private ChatResponseProto() {}
    
    private static final ChatResponseProto defaultInstance = new ChatResponseProto();
    public static ChatResponseProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChatResponseProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatResponseProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatResponseProto_fieldAccessorTable;
    }
    
    // optional int32 event = 1;
    public static final int EVENT_FIELD_NUMBER = 1;
    private boolean hasEvent;
    private int event_ = 0;
    public boolean hasEvent() { return hasEvent; }
    public int getEvent() { return event_; }
    
    // repeated .com.lvl6.proto.UserProto recipients = 2;
    public static final int RECIPIENTS_FIELD_NUMBER = 2;
    private java.util.List<com.lvl6.proto.InfoProto.UserProto> recipients_ =
      java.util.Collections.emptyList();
    public java.util.List<com.lvl6.proto.InfoProto.UserProto> getRecipientsList() {
      return recipients_;
    }
    public int getRecipientsCount() { return recipients_.size(); }
    public com.lvl6.proto.InfoProto.UserProto getRecipients(int index) {
      return recipients_.get(index);
    }
    
    // required string message = 3;
    public static final int MESSAGE_FIELD_NUMBER = 3;
    private boolean hasMessage;
    private java.lang.String message_ = "";
    public boolean hasMessage() { return hasMessage; }
    public java.lang.String getMessage() { return message_; }
    
    public final boolean isInitialized() {
      if (!hasMessage) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasEvent()) {
        output.writeInt32(1, getEvent());
      }
      for (com.lvl6.proto.InfoProto.UserProto element : getRecipientsList()) {
        output.writeMessage(2, element);
      }
      if (hasMessage()) {
        output.writeString(3, getMessage());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasEvent()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getEvent());
      }
      for (com.lvl6.proto.InfoProto.UserProto element : getRecipientsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      if (hasMessage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getMessage());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.proto.EventProto.ChatResponseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.lvl6.proto.EventProto.ChatResponseProto result;
      
      // Construct using com.lvl6.proto.EventProto.ChatResponseProto.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.lvl6.proto.EventProto.ChatResponseProto();
        return builder;
      }
      
      protected com.lvl6.proto.EventProto.ChatResponseProto internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.lvl6.proto.EventProto.ChatResponseProto();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.proto.EventProto.ChatResponseProto.getDescriptor();
      }
      
      public com.lvl6.proto.EventProto.ChatResponseProto getDefaultInstanceForType() {
        return com.lvl6.proto.EventProto.ChatResponseProto.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.lvl6.proto.EventProto.ChatResponseProto build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.lvl6.proto.EventProto.ChatResponseProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.lvl6.proto.EventProto.ChatResponseProto buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.recipients_ != java.util.Collections.EMPTY_LIST) {
          result.recipients_ =
            java.util.Collections.unmodifiableList(result.recipients_);
        }
        com.lvl6.proto.EventProto.ChatResponseProto returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.proto.EventProto.ChatResponseProto) {
          return mergeFrom((com.lvl6.proto.EventProto.ChatResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.proto.EventProto.ChatResponseProto other) {
        if (other == com.lvl6.proto.EventProto.ChatResponseProto.getDefaultInstance()) return this;
        if (other.hasEvent()) {
          setEvent(other.getEvent());
        }
        if (!other.recipients_.isEmpty()) {
          if (result.recipients_.isEmpty()) {
            result.recipients_ = new java.util.ArrayList<com.lvl6.proto.InfoProto.UserProto>();
          }
          result.recipients_.addAll(other.recipients_);
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setEvent(input.readInt32());
              break;
            }
            case 18: {
              com.lvl6.proto.InfoProto.UserProto.Builder subBuilder = com.lvl6.proto.InfoProto.UserProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRecipients(subBuilder.buildPartial());
              break;
            }
            case 26: {
              setMessage(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional int32 event = 1;
      public boolean hasEvent() {
        return result.hasEvent();
      }
      public int getEvent() {
        return result.getEvent();
      }
      public Builder setEvent(int value) {
        result.hasEvent = true;
        result.event_ = value;
        return this;
      }
      public Builder clearEvent() {
        result.hasEvent = false;
        result.event_ = 0;
        return this;
      }
      
      // repeated .com.lvl6.proto.UserProto recipients = 2;
      public java.util.List<com.lvl6.proto.InfoProto.UserProto> getRecipientsList() {
        return java.util.Collections.unmodifiableList(result.recipients_);
      }
      public int getRecipientsCount() {
        return result.getRecipientsCount();
      }
      public com.lvl6.proto.InfoProto.UserProto getRecipients(int index) {
        return result.getRecipients(index);
      }
      public Builder setRecipients(int index, com.lvl6.proto.InfoProto.UserProto value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.recipients_.set(index, value);
        return this;
      }
      public Builder setRecipients(int index, com.lvl6.proto.InfoProto.UserProto.Builder builderForValue) {
        result.recipients_.set(index, builderForValue.build());
        return this;
      }
      public Builder addRecipients(com.lvl6.proto.InfoProto.UserProto value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.recipients_.isEmpty()) {
          result.recipients_ = new java.util.ArrayList<com.lvl6.proto.InfoProto.UserProto>();
        }
        result.recipients_.add(value);
        return this;
      }
      public Builder addRecipients(com.lvl6.proto.InfoProto.UserProto.Builder builderForValue) {
        if (result.recipients_.isEmpty()) {
          result.recipients_ = new java.util.ArrayList<com.lvl6.proto.InfoProto.UserProto>();
        }
        result.recipients_.add(builderForValue.build());
        return this;
      }
      public Builder addAllRecipients(
          java.lang.Iterable<? extends com.lvl6.proto.InfoProto.UserProto> values) {
        if (result.recipients_.isEmpty()) {
          result.recipients_ = new java.util.ArrayList<com.lvl6.proto.InfoProto.UserProto>();
        }
        super.addAll(values, result.recipients_);
        return this;
      }
      public Builder clearRecipients() {
        result.recipients_ = java.util.Collections.emptyList();
        return this;
      }
      
      // required string message = 3;
      public boolean hasMessage() {
        return result.hasMessage();
      }
      public java.lang.String getMessage() {
        return result.getMessage();
      }
      public Builder setMessage(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessage = true;
        result.message_ = value;
        return this;
      }
      public Builder clearMessage() {
        result.hasMessage = false;
        result.message_ = getDefaultInstance().getMessage();
        return this;
      }
    }
    
    static {
      com.lvl6.proto.EventProto.getDescriptor();
    }
    
    static {
      com.lvl6.proto.EventProto.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lvl6_proto_ChatRequestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lvl6_proto_ChatRequestProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lvl6_proto_ChatResponseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lvl6_proto_ChatResponseProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Event.proto\022\016com.lvl6.proto\032\nUser.prot" +
      "o\"s\n\020ChatRequestProto\022\020\n\010playerId\030\001 \002(\005\022" +
      "\r\n\005event\030\002 \001(\005\022-\n\nrecipients\030\003 \003(\0132\031.com" +
      ".lvl6.proto.UserProto\022\017\n\007message\030\004 \002(\t\"b" +
      "\n\021ChatResponseProto\022\r\n\005event\030\001 \001(\005\022-\n\nre" +
      "cipients\030\002 \003(\0132\031.com.lvl6.proto.UserProt" +
      "o\022\017\n\007message\030\003 \002(\tB\014B\nEventProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_lvl6_proto_ChatRequestProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_lvl6_proto_ChatRequestProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_lvl6_proto_ChatRequestProto_descriptor,
              new java.lang.String[] { "PlayerId", "Event", "Recipients", "Message", },
              com.lvl6.proto.EventProto.ChatRequestProto.class,
              com.lvl6.proto.EventProto.ChatRequestProto.Builder.class);
          internal_static_com_lvl6_proto_ChatResponseProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_lvl6_proto_ChatResponseProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_lvl6_proto_ChatResponseProto_descriptor,
              new java.lang.String[] { "Event", "Recipients", "Message", },
              com.lvl6.proto.EventProto.ChatResponseProto.class,
              com.lvl6.proto.EventProto.ChatResponseProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lvl6.proto.InfoProto.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
