// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package com.lvl6.proto;

public final class EventProto {
  private EventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChatRequestProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .com.lvl6.proto.MinimumUserProto sender = 1;
    boolean hasSender();
    com.lvl6.proto.InfoProto.MinimumUserProto getSender();
    com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder getSenderOrBuilder();
    
    // repeated .com.lvl6.proto.MinimumUserProto recipients = 2;
    java.util.List<com.lvl6.proto.InfoProto.MinimumUserProto> 
        getRecipientsList();
    com.lvl6.proto.InfoProto.MinimumUserProto getRecipients(int index);
    int getRecipientsCount();
    java.util.List<? extends com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder> 
        getRecipientsOrBuilderList();
    com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder getRecipientsOrBuilder(
        int index);
    
    // required string message = 3;
    boolean hasMessage();
    String getMessage();
  }
  public static final class ChatRequestProto extends
      com.google.protobuf.GeneratedMessage
      implements ChatRequestProtoOrBuilder {
    // Use ChatRequestProto.newBuilder() to construct.
    private ChatRequestProto(Builder builder) {
      super(builder);
    }
    private ChatRequestProto(boolean noInit) {}
    
    private static final ChatRequestProto defaultInstance;
    public static ChatRequestProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChatRequestProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatRequestProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatRequestProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .com.lvl6.proto.MinimumUserProto sender = 1;
    public static final int SENDER_FIELD_NUMBER = 1;
    private com.lvl6.proto.InfoProto.MinimumUserProto sender_;
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.lvl6.proto.InfoProto.MinimumUserProto getSender() {
      return sender_;
    }
    public com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder getSenderOrBuilder() {
      return sender_;
    }
    
    // repeated .com.lvl6.proto.MinimumUserProto recipients = 2;
    public static final int RECIPIENTS_FIELD_NUMBER = 2;
    private java.util.List<com.lvl6.proto.InfoProto.MinimumUserProto> recipients_;
    public java.util.List<com.lvl6.proto.InfoProto.MinimumUserProto> getRecipientsList() {
      return recipients_;
    }
    public java.util.List<? extends com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder> 
        getRecipientsOrBuilderList() {
      return recipients_;
    }
    public int getRecipientsCount() {
      return recipients_.size();
    }
    public com.lvl6.proto.InfoProto.MinimumUserProto getRecipients(int index) {
      return recipients_.get(index);
    }
    public com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder getRecipientsOrBuilder(
        int index) {
      return recipients_.get(index);
    }
    
    // required string message = 3;
    public static final int MESSAGE_FIELD_NUMBER = 3;
    private java.lang.Object message_;
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          message_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      sender_ = com.lvl6.proto.InfoProto.MinimumUserProto.getDefaultInstance();
      recipients_ = java.util.Collections.emptyList();
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSender()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSender().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRecipientsCount(); i++) {
        if (!getRecipients(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, sender_);
      }
      for (int i = 0; i < recipients_.size(); i++) {
        output.writeMessage(2, recipients_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sender_);
      }
      for (int i = 0; i < recipients_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, recipients_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.proto.EventProto.ChatRequestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.proto.EventProto.ChatRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatRequestProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatRequestProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.proto.EventProto.ChatRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSenderFieldBuilder();
          getRecipientsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.proto.InfoProto.MinimumUserProto.getDefaultInstance();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (recipientsBuilder_ == null) {
          recipients_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          recipientsBuilder_.clear();
        }
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.proto.EventProto.ChatRequestProto.getDescriptor();
      }
      
      public com.lvl6.proto.EventProto.ChatRequestProto getDefaultInstanceForType() {
        return com.lvl6.proto.EventProto.ChatRequestProto.getDefaultInstance();
      }
      
      public com.lvl6.proto.EventProto.ChatRequestProto build() {
        com.lvl6.proto.EventProto.ChatRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.proto.EventProto.ChatRequestProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.proto.EventProto.ChatRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.proto.EventProto.ChatRequestProto buildPartial() {
        com.lvl6.proto.EventProto.ChatRequestProto result = new com.lvl6.proto.EventProto.ChatRequestProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (senderBuilder_ == null) {
          result.sender_ = sender_;
        } else {
          result.sender_ = senderBuilder_.build();
        }
        if (recipientsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            recipients_ = java.util.Collections.unmodifiableList(recipients_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.recipients_ = recipients_;
        } else {
          result.recipients_ = recipientsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.proto.EventProto.ChatRequestProto) {
          return mergeFrom((com.lvl6.proto.EventProto.ChatRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.proto.EventProto.ChatRequestProto other) {
        if (other == com.lvl6.proto.EventProto.ChatRequestProto.getDefaultInstance()) return this;
        if (other.hasSender()) {
          mergeSender(other.getSender());
        }
        if (recipientsBuilder_ == null) {
          if (!other.recipients_.isEmpty()) {
            if (recipients_.isEmpty()) {
              recipients_ = other.recipients_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRecipientsIsMutable();
              recipients_.addAll(other.recipients_);
            }
            onChanged();
          }
        } else {
          if (!other.recipients_.isEmpty()) {
            if (recipientsBuilder_.isEmpty()) {
              recipientsBuilder_.dispose();
              recipientsBuilder_ = null;
              recipients_ = other.recipients_;
              bitField0_ = (bitField0_ & ~0x00000002);
              recipientsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRecipientsFieldBuilder() : null;
            } else {
              recipientsBuilder_.addAllMessages(other.recipients_);
            }
          }
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSender()) {
          
          return false;
        }
        if (!hasMessage()) {
          
          return false;
        }
        if (!getSender().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getRecipientsCount(); i++) {
          if (!getRecipients(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.lvl6.proto.InfoProto.MinimumUserProto.Builder subBuilder = com.lvl6.proto.InfoProto.MinimumUserProto.newBuilder();
              if (hasSender()) {
                subBuilder.mergeFrom(getSender());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSender(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.lvl6.proto.InfoProto.MinimumUserProto.Builder subBuilder = com.lvl6.proto.InfoProto.MinimumUserProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRecipients(subBuilder.buildPartial());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              message_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.lvl6.proto.MinimumUserProto sender = 1;
      private com.lvl6.proto.InfoProto.MinimumUserProto sender_ = com.lvl6.proto.InfoProto.MinimumUserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.InfoProto.MinimumUserProto, com.lvl6.proto.InfoProto.MinimumUserProto.Builder, com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder> senderBuilder_;
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.lvl6.proto.InfoProto.MinimumUserProto getSender() {
        if (senderBuilder_ == null) {
          return sender_;
        } else {
          return senderBuilder_.getMessage();
        }
      }
      public Builder setSender(com.lvl6.proto.InfoProto.MinimumUserProto value) {
        if (senderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sender_ = value;
          onChanged();
        } else {
          senderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setSender(
          com.lvl6.proto.InfoProto.MinimumUserProto.Builder builderForValue) {
        if (senderBuilder_ == null) {
          sender_ = builderForValue.build();
          onChanged();
        } else {
          senderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeSender(com.lvl6.proto.InfoProto.MinimumUserProto value) {
        if (senderBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              sender_ != com.lvl6.proto.InfoProto.MinimumUserProto.getDefaultInstance()) {
            sender_ =
              com.lvl6.proto.InfoProto.MinimumUserProto.newBuilder(sender_).mergeFrom(value).buildPartial();
          } else {
            sender_ = value;
          }
          onChanged();
        } else {
          senderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearSender() {
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.proto.InfoProto.MinimumUserProto.getDefaultInstance();
          onChanged();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.lvl6.proto.InfoProto.MinimumUserProto.Builder getSenderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSenderFieldBuilder().getBuilder();
      }
      public com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder getSenderOrBuilder() {
        if (senderBuilder_ != null) {
          return senderBuilder_.getMessageOrBuilder();
        } else {
          return sender_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.InfoProto.MinimumUserProto, com.lvl6.proto.InfoProto.MinimumUserProto.Builder, com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder> 
          getSenderFieldBuilder() {
        if (senderBuilder_ == null) {
          senderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.proto.InfoProto.MinimumUserProto, com.lvl6.proto.InfoProto.MinimumUserProto.Builder, com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder>(
                  sender_,
                  getParentForChildren(),
                  isClean());
          sender_ = null;
        }
        return senderBuilder_;
      }
      
      // repeated .com.lvl6.proto.MinimumUserProto recipients = 2;
      private java.util.List<com.lvl6.proto.InfoProto.MinimumUserProto> recipients_ =
        java.util.Collections.emptyList();
      private void ensureRecipientsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          recipients_ = new java.util.ArrayList<com.lvl6.proto.InfoProto.MinimumUserProto>(recipients_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.proto.InfoProto.MinimumUserProto, com.lvl6.proto.InfoProto.MinimumUserProto.Builder, com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder> recipientsBuilder_;
      
      public java.util.List<com.lvl6.proto.InfoProto.MinimumUserProto> getRecipientsList() {
        if (recipientsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(recipients_);
        } else {
          return recipientsBuilder_.getMessageList();
        }
      }
      public int getRecipientsCount() {
        if (recipientsBuilder_ == null) {
          return recipients_.size();
        } else {
          return recipientsBuilder_.getCount();
        }
      }
      public com.lvl6.proto.InfoProto.MinimumUserProto getRecipients(int index) {
        if (recipientsBuilder_ == null) {
          return recipients_.get(index);
        } else {
          return recipientsBuilder_.getMessage(index);
        }
      }
      public Builder setRecipients(
          int index, com.lvl6.proto.InfoProto.MinimumUserProto value) {
        if (recipientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecipientsIsMutable();
          recipients_.set(index, value);
          onChanged();
        } else {
          recipientsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setRecipients(
          int index, com.lvl6.proto.InfoProto.MinimumUserProto.Builder builderForValue) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.set(index, builderForValue.build());
          onChanged();
        } else {
          recipientsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addRecipients(com.lvl6.proto.InfoProto.MinimumUserProto value) {
        if (recipientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecipientsIsMutable();
          recipients_.add(value);
          onChanged();
        } else {
          recipientsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addRecipients(
          int index, com.lvl6.proto.InfoProto.MinimumUserProto value) {
        if (recipientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecipientsIsMutable();
          recipients_.add(index, value);
          onChanged();
        } else {
          recipientsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addRecipients(
          com.lvl6.proto.InfoProto.MinimumUserProto.Builder builderForValue) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.add(builderForValue.build());
          onChanged();
        } else {
          recipientsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addRecipients(
          int index, com.lvl6.proto.InfoProto.MinimumUserProto.Builder builderForValue) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.add(index, builderForValue.build());
          onChanged();
        } else {
          recipientsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllRecipients(
          java.lang.Iterable<? extends com.lvl6.proto.InfoProto.MinimumUserProto> values) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          super.addAll(values, recipients_);
          onChanged();
        } else {
          recipientsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearRecipients() {
        if (recipientsBuilder_ == null) {
          recipients_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          recipientsBuilder_.clear();
        }
        return this;
      }
      public Builder removeRecipients(int index) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.remove(index);
          onChanged();
        } else {
          recipientsBuilder_.remove(index);
        }
        return this;
      }
      public com.lvl6.proto.InfoProto.MinimumUserProto.Builder getRecipientsBuilder(
          int index) {
        return getRecipientsFieldBuilder().getBuilder(index);
      }
      public com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder getRecipientsOrBuilder(
          int index) {
        if (recipientsBuilder_ == null) {
          return recipients_.get(index);  } else {
          return recipientsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder> 
           getRecipientsOrBuilderList() {
        if (recipientsBuilder_ != null) {
          return recipientsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(recipients_);
        }
      }
      public com.lvl6.proto.InfoProto.MinimumUserProto.Builder addRecipientsBuilder() {
        return getRecipientsFieldBuilder().addBuilder(
            com.lvl6.proto.InfoProto.MinimumUserProto.getDefaultInstance());
      }
      public com.lvl6.proto.InfoProto.MinimumUserProto.Builder addRecipientsBuilder(
          int index) {
        return getRecipientsFieldBuilder().addBuilder(
            index, com.lvl6.proto.InfoProto.MinimumUserProto.getDefaultInstance());
      }
      public java.util.List<com.lvl6.proto.InfoProto.MinimumUserProto.Builder> 
           getRecipientsBuilderList() {
        return getRecipientsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.proto.InfoProto.MinimumUserProto, com.lvl6.proto.InfoProto.MinimumUserProto.Builder, com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder> 
          getRecipientsFieldBuilder() {
        if (recipientsBuilder_ == null) {
          recipientsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.lvl6.proto.InfoProto.MinimumUserProto, com.lvl6.proto.InfoProto.MinimumUserProto.Builder, com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder>(
                  recipients_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          recipients_ = null;
        }
        return recipientsBuilder_;
      }
      
      // required string message = 3;
      private java.lang.Object message_ = "";
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      void setMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.lvl6.proto.ChatRequestProto)
    }
    
    static {
      defaultInstance = new ChatRequestProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.lvl6.proto.ChatRequestProto)
  }
  
  public interface ChatResponseProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .com.lvl6.proto.MinimumUserProto sender = 1;
    boolean hasSender();
    com.lvl6.proto.InfoProto.MinimumUserProto getSender();
    com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder getSenderOrBuilder();
    
    // required string message = 2;
    boolean hasMessage();
    String getMessage();
  }
  public static final class ChatResponseProto extends
      com.google.protobuf.GeneratedMessage
      implements ChatResponseProtoOrBuilder {
    // Use ChatResponseProto.newBuilder() to construct.
    private ChatResponseProto(Builder builder) {
      super(builder);
    }
    private ChatResponseProto(boolean noInit) {}
    
    private static final ChatResponseProto defaultInstance;
    public static ChatResponseProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChatResponseProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatResponseProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatResponseProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .com.lvl6.proto.MinimumUserProto sender = 1;
    public static final int SENDER_FIELD_NUMBER = 1;
    private com.lvl6.proto.InfoProto.MinimumUserProto sender_;
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.lvl6.proto.InfoProto.MinimumUserProto getSender() {
      return sender_;
    }
    public com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder getSenderOrBuilder() {
      return sender_;
    }
    
    // required string message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.Object message_;
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          message_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      sender_ = com.lvl6.proto.InfoProto.MinimumUserProto.getDefaultInstance();
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSender()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSender().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.proto.EventProto.ChatResponseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.proto.EventProto.ChatResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatResponseProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatResponseProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.proto.EventProto.ChatResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSenderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.proto.InfoProto.MinimumUserProto.getDefaultInstance();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.proto.EventProto.ChatResponseProto.getDescriptor();
      }
      
      public com.lvl6.proto.EventProto.ChatResponseProto getDefaultInstanceForType() {
        return com.lvl6.proto.EventProto.ChatResponseProto.getDefaultInstance();
      }
      
      public com.lvl6.proto.EventProto.ChatResponseProto build() {
        com.lvl6.proto.EventProto.ChatResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.proto.EventProto.ChatResponseProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.proto.EventProto.ChatResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.proto.EventProto.ChatResponseProto buildPartial() {
        com.lvl6.proto.EventProto.ChatResponseProto result = new com.lvl6.proto.EventProto.ChatResponseProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (senderBuilder_ == null) {
          result.sender_ = sender_;
        } else {
          result.sender_ = senderBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.proto.EventProto.ChatResponseProto) {
          return mergeFrom((com.lvl6.proto.EventProto.ChatResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.proto.EventProto.ChatResponseProto other) {
        if (other == com.lvl6.proto.EventProto.ChatResponseProto.getDefaultInstance()) return this;
        if (other.hasSender()) {
          mergeSender(other.getSender());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSender()) {
          
          return false;
        }
        if (!hasMessage()) {
          
          return false;
        }
        if (!getSender().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.lvl6.proto.InfoProto.MinimumUserProto.Builder subBuilder = com.lvl6.proto.InfoProto.MinimumUserProto.newBuilder();
              if (hasSender()) {
                subBuilder.mergeFrom(getSender());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSender(subBuilder.buildPartial());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              message_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.lvl6.proto.MinimumUserProto sender = 1;
      private com.lvl6.proto.InfoProto.MinimumUserProto sender_ = com.lvl6.proto.InfoProto.MinimumUserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.InfoProto.MinimumUserProto, com.lvl6.proto.InfoProto.MinimumUserProto.Builder, com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder> senderBuilder_;
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.lvl6.proto.InfoProto.MinimumUserProto getSender() {
        if (senderBuilder_ == null) {
          return sender_;
        } else {
          return senderBuilder_.getMessage();
        }
      }
      public Builder setSender(com.lvl6.proto.InfoProto.MinimumUserProto value) {
        if (senderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sender_ = value;
          onChanged();
        } else {
          senderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setSender(
          com.lvl6.proto.InfoProto.MinimumUserProto.Builder builderForValue) {
        if (senderBuilder_ == null) {
          sender_ = builderForValue.build();
          onChanged();
        } else {
          senderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeSender(com.lvl6.proto.InfoProto.MinimumUserProto value) {
        if (senderBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              sender_ != com.lvl6.proto.InfoProto.MinimumUserProto.getDefaultInstance()) {
            sender_ =
              com.lvl6.proto.InfoProto.MinimumUserProto.newBuilder(sender_).mergeFrom(value).buildPartial();
          } else {
            sender_ = value;
          }
          onChanged();
        } else {
          senderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearSender() {
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.proto.InfoProto.MinimumUserProto.getDefaultInstance();
          onChanged();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.lvl6.proto.InfoProto.MinimumUserProto.Builder getSenderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSenderFieldBuilder().getBuilder();
      }
      public com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder getSenderOrBuilder() {
        if (senderBuilder_ != null) {
          return senderBuilder_.getMessageOrBuilder();
        } else {
          return sender_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.proto.InfoProto.MinimumUserProto, com.lvl6.proto.InfoProto.MinimumUserProto.Builder, com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder> 
          getSenderFieldBuilder() {
        if (senderBuilder_ == null) {
          senderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.proto.InfoProto.MinimumUserProto, com.lvl6.proto.InfoProto.MinimumUserProto.Builder, com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder>(
                  sender_,
                  getParentForChildren(),
                  isClean());
          sender_ = null;
        }
        return senderBuilder_;
      }
      
      // required string message = 2;
      private java.lang.Object message_ = "";
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      void setMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.lvl6.proto.ChatResponseProto)
    }
    
    static {
      defaultInstance = new ChatResponseProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.lvl6.proto.ChatResponseProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lvl6_proto_ChatRequestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lvl6_proto_ChatRequestProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lvl6_proto_ChatResponseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lvl6_proto_ChatResponseProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Event.proto\022\016com.lvl6.proto\032\nInfo.prot" +
      "o\"\213\001\n\020ChatRequestProto\0220\n\006sender\030\001 \002(\0132 " +
      ".com.lvl6.proto.MinimumUserProto\0224\n\nreci" +
      "pients\030\002 \003(\0132 .com.lvl6.proto.MinimumUse" +
      "rProto\022\017\n\007message\030\003 \002(\t\"V\n\021ChatResponseP" +
      "roto\0220\n\006sender\030\001 \002(\0132 .com.lvl6.proto.Mi" +
      "nimumUserProto\022\017\n\007message\030\002 \002(\tB\014B\nEvent" +
      "Proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_lvl6_proto_ChatRequestProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_lvl6_proto_ChatRequestProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_lvl6_proto_ChatRequestProto_descriptor,
              new java.lang.String[] { "Sender", "Recipients", "Message", },
              com.lvl6.proto.EventProto.ChatRequestProto.class,
              com.lvl6.proto.EventProto.ChatRequestProto.Builder.class);
          internal_static_com_lvl6_proto_ChatResponseProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_lvl6_proto_ChatResponseProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_lvl6_proto_ChatResponseProto_descriptor,
              new java.lang.String[] { "Sender", "Message", },
              com.lvl6.proto.EventProto.ChatResponseProto.class,
              com.lvl6.proto.EventProto.ChatResponseProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lvl6.proto.InfoProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
