// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package com.lvl6.proto;

public final class EventProto {
  private EventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChatRequestProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 event = 1;
    boolean hasEvent();
    int getEvent();
    
    // repeated .com.lvl6.proto.UserProto recipients = 2;
    java.util.List<com.lvl6.proto.InfoProto.UserProto> 
        getRecipientsList();
    com.lvl6.proto.InfoProto.UserProto getRecipients(int index);
    int getRecipientsCount();
    java.util.List<? extends com.lvl6.proto.InfoProto.UserProtoOrBuilder> 
        getRecipientsOrBuilderList();
    com.lvl6.proto.InfoProto.UserProtoOrBuilder getRecipientsOrBuilder(
        int index);
  }
  public static final class ChatRequestProto extends
      com.google.protobuf.GeneratedMessage
      implements ChatRequestProtoOrBuilder {
    // Use ChatRequestProto.newBuilder() to construct.
    private ChatRequestProto(Builder builder) {
      super(builder);
    }
    private ChatRequestProto(boolean noInit) {}
    
    private static final ChatRequestProto defaultInstance;
    public static ChatRequestProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChatRequestProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatRequestProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatRequestProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 event = 1;
    public static final int EVENT_FIELD_NUMBER = 1;
    private int event_;
    public boolean hasEvent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getEvent() {
      return event_;
    }
    
    // repeated .com.lvl6.proto.UserProto recipients = 2;
    public static final int RECIPIENTS_FIELD_NUMBER = 2;
    private java.util.List<com.lvl6.proto.InfoProto.UserProto> recipients_;
    public java.util.List<com.lvl6.proto.InfoProto.UserProto> getRecipientsList() {
      return recipients_;
    }
    public java.util.List<? extends com.lvl6.proto.InfoProto.UserProtoOrBuilder> 
        getRecipientsOrBuilderList() {
      return recipients_;
    }
    public int getRecipientsCount() {
      return recipients_.size();
    }
    public com.lvl6.proto.InfoProto.UserProto getRecipients(int index) {
      return recipients_.get(index);
    }
    public com.lvl6.proto.InfoProto.UserProtoOrBuilder getRecipientsOrBuilder(
        int index) {
      return recipients_.get(index);
    }
    
    private void initFields() {
      event_ = 0;
      recipients_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, event_);
      }
      for (int i = 0; i < recipients_.size(); i++) {
        output.writeMessage(2, recipients_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, event_);
      }
      for (int i = 0; i < recipients_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, recipients_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.proto.EventProto.ChatRequestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.proto.EventProto.ChatRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatRequestProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatRequestProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.proto.EventProto.ChatRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRecipientsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        event_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (recipientsBuilder_ == null) {
          recipients_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          recipientsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.proto.EventProto.ChatRequestProto.getDescriptor();
      }
      
      public com.lvl6.proto.EventProto.ChatRequestProto getDefaultInstanceForType() {
        return com.lvl6.proto.EventProto.ChatRequestProto.getDefaultInstance();
      }
      
      public com.lvl6.proto.EventProto.ChatRequestProto build() {
        com.lvl6.proto.EventProto.ChatRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.proto.EventProto.ChatRequestProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.proto.EventProto.ChatRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.proto.EventProto.ChatRequestProto buildPartial() {
        com.lvl6.proto.EventProto.ChatRequestProto result = new com.lvl6.proto.EventProto.ChatRequestProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.event_ = event_;
        if (recipientsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            recipients_ = java.util.Collections.unmodifiableList(recipients_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.recipients_ = recipients_;
        } else {
          result.recipients_ = recipientsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.proto.EventProto.ChatRequestProto) {
          return mergeFrom((com.lvl6.proto.EventProto.ChatRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.proto.EventProto.ChatRequestProto other) {
        if (other == com.lvl6.proto.EventProto.ChatRequestProto.getDefaultInstance()) return this;
        if (other.hasEvent()) {
          setEvent(other.getEvent());
        }
        if (recipientsBuilder_ == null) {
          if (!other.recipients_.isEmpty()) {
            if (recipients_.isEmpty()) {
              recipients_ = other.recipients_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRecipientsIsMutable();
              recipients_.addAll(other.recipients_);
            }
            onChanged();
          }
        } else {
          if (!other.recipients_.isEmpty()) {
            if (recipientsBuilder_.isEmpty()) {
              recipientsBuilder_.dispose();
              recipientsBuilder_ = null;
              recipients_ = other.recipients_;
              bitField0_ = (bitField0_ & ~0x00000002);
              recipientsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRecipientsFieldBuilder() : null;
            } else {
              recipientsBuilder_.addAllMessages(other.recipients_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              event_ = input.readInt32();
              break;
            }
            case 18: {
              com.lvl6.proto.InfoProto.UserProto.Builder subBuilder = com.lvl6.proto.InfoProto.UserProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRecipients(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 event = 1;
      private int event_ ;
      public boolean hasEvent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getEvent() {
        return event_;
      }
      public Builder setEvent(int value) {
        bitField0_ |= 0x00000001;
        event_ = value;
        onChanged();
        return this;
      }
      public Builder clearEvent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        event_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .com.lvl6.proto.UserProto recipients = 2;
      private java.util.List<com.lvl6.proto.InfoProto.UserProto> recipients_ =
        java.util.Collections.emptyList();
      private void ensureRecipientsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          recipients_ = new java.util.ArrayList<com.lvl6.proto.InfoProto.UserProto>(recipients_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.proto.InfoProto.UserProto, com.lvl6.proto.InfoProto.UserProto.Builder, com.lvl6.proto.InfoProto.UserProtoOrBuilder> recipientsBuilder_;
      
      public java.util.List<com.lvl6.proto.InfoProto.UserProto> getRecipientsList() {
        if (recipientsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(recipients_);
        } else {
          return recipientsBuilder_.getMessageList();
        }
      }
      public int getRecipientsCount() {
        if (recipientsBuilder_ == null) {
          return recipients_.size();
        } else {
          return recipientsBuilder_.getCount();
        }
      }
      public com.lvl6.proto.InfoProto.UserProto getRecipients(int index) {
        if (recipientsBuilder_ == null) {
          return recipients_.get(index);
        } else {
          return recipientsBuilder_.getMessage(index);
        }
      }
      public Builder setRecipients(
          int index, com.lvl6.proto.InfoProto.UserProto value) {
        if (recipientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecipientsIsMutable();
          recipients_.set(index, value);
          onChanged();
        } else {
          recipientsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setRecipients(
          int index, com.lvl6.proto.InfoProto.UserProto.Builder builderForValue) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.set(index, builderForValue.build());
          onChanged();
        } else {
          recipientsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addRecipients(com.lvl6.proto.InfoProto.UserProto value) {
        if (recipientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecipientsIsMutable();
          recipients_.add(value);
          onChanged();
        } else {
          recipientsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addRecipients(
          int index, com.lvl6.proto.InfoProto.UserProto value) {
        if (recipientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecipientsIsMutable();
          recipients_.add(index, value);
          onChanged();
        } else {
          recipientsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addRecipients(
          com.lvl6.proto.InfoProto.UserProto.Builder builderForValue) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.add(builderForValue.build());
          onChanged();
        } else {
          recipientsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addRecipients(
          int index, com.lvl6.proto.InfoProto.UserProto.Builder builderForValue) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.add(index, builderForValue.build());
          onChanged();
        } else {
          recipientsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllRecipients(
          java.lang.Iterable<? extends com.lvl6.proto.InfoProto.UserProto> values) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          super.addAll(values, recipients_);
          onChanged();
        } else {
          recipientsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearRecipients() {
        if (recipientsBuilder_ == null) {
          recipients_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          recipientsBuilder_.clear();
        }
        return this;
      }
      public Builder removeRecipients(int index) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.remove(index);
          onChanged();
        } else {
          recipientsBuilder_.remove(index);
        }
        return this;
      }
      public com.lvl6.proto.InfoProto.UserProto.Builder getRecipientsBuilder(
          int index) {
        return getRecipientsFieldBuilder().getBuilder(index);
      }
      public com.lvl6.proto.InfoProto.UserProtoOrBuilder getRecipientsOrBuilder(
          int index) {
        if (recipientsBuilder_ == null) {
          return recipients_.get(index);  } else {
          return recipientsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.lvl6.proto.InfoProto.UserProtoOrBuilder> 
           getRecipientsOrBuilderList() {
        if (recipientsBuilder_ != null) {
          return recipientsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(recipients_);
        }
      }
      public com.lvl6.proto.InfoProto.UserProto.Builder addRecipientsBuilder() {
        return getRecipientsFieldBuilder().addBuilder(
            com.lvl6.proto.InfoProto.UserProto.getDefaultInstance());
      }
      public com.lvl6.proto.InfoProto.UserProto.Builder addRecipientsBuilder(
          int index) {
        return getRecipientsFieldBuilder().addBuilder(
            index, com.lvl6.proto.InfoProto.UserProto.getDefaultInstance());
      }
      public java.util.List<com.lvl6.proto.InfoProto.UserProto.Builder> 
           getRecipientsBuilderList() {
        return getRecipientsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.proto.InfoProto.UserProto, com.lvl6.proto.InfoProto.UserProto.Builder, com.lvl6.proto.InfoProto.UserProtoOrBuilder> 
          getRecipientsFieldBuilder() {
        if (recipientsBuilder_ == null) {
          recipientsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.lvl6.proto.InfoProto.UserProto, com.lvl6.proto.InfoProto.UserProto.Builder, com.lvl6.proto.InfoProto.UserProtoOrBuilder>(
                  recipients_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          recipients_ = null;
        }
        return recipientsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.lvl6.proto.ChatRequestProto)
    }
    
    static {
      defaultInstance = new ChatRequestProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.lvl6.proto.ChatRequestProto)
  }
  
  public interface ChatResponseProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 event = 1;
    boolean hasEvent();
    int getEvent();
    
    // repeated .com.lvl6.proto.UserProto recipients = 2;
    java.util.List<com.lvl6.proto.InfoProto.UserProto> 
        getRecipientsList();
    com.lvl6.proto.InfoProto.UserProto getRecipients(int index);
    int getRecipientsCount();
    java.util.List<? extends com.lvl6.proto.InfoProto.UserProtoOrBuilder> 
        getRecipientsOrBuilderList();
    com.lvl6.proto.InfoProto.UserProtoOrBuilder getRecipientsOrBuilder(
        int index);
  }
  public static final class ChatResponseProto extends
      com.google.protobuf.GeneratedMessage
      implements ChatResponseProtoOrBuilder {
    // Use ChatResponseProto.newBuilder() to construct.
    private ChatResponseProto(Builder builder) {
      super(builder);
    }
    private ChatResponseProto(boolean noInit) {}
    
    private static final ChatResponseProto defaultInstance;
    public static ChatResponseProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChatResponseProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatResponseProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatResponseProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 event = 1;
    public static final int EVENT_FIELD_NUMBER = 1;
    private int event_;
    public boolean hasEvent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getEvent() {
      return event_;
    }
    
    // repeated .com.lvl6.proto.UserProto recipients = 2;
    public static final int RECIPIENTS_FIELD_NUMBER = 2;
    private java.util.List<com.lvl6.proto.InfoProto.UserProto> recipients_;
    public java.util.List<com.lvl6.proto.InfoProto.UserProto> getRecipientsList() {
      return recipients_;
    }
    public java.util.List<? extends com.lvl6.proto.InfoProto.UserProtoOrBuilder> 
        getRecipientsOrBuilderList() {
      return recipients_;
    }
    public int getRecipientsCount() {
      return recipients_.size();
    }
    public com.lvl6.proto.InfoProto.UserProto getRecipients(int index) {
      return recipients_.get(index);
    }
    public com.lvl6.proto.InfoProto.UserProtoOrBuilder getRecipientsOrBuilder(
        int index) {
      return recipients_.get(index);
    }
    
    private void initFields() {
      event_ = 0;
      recipients_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, event_);
      }
      for (int i = 0; i < recipients_.size(); i++) {
        output.writeMessage(2, recipients_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, event_);
      }
      for (int i = 0; i < recipients_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, recipients_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.EventProto.ChatResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.proto.EventProto.ChatResponseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.proto.EventProto.ChatResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatResponseProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.proto.EventProto.internal_static_com_lvl6_proto_ChatResponseProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.proto.EventProto.ChatResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRecipientsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        event_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (recipientsBuilder_ == null) {
          recipients_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          recipientsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.proto.EventProto.ChatResponseProto.getDescriptor();
      }
      
      public com.lvl6.proto.EventProto.ChatResponseProto getDefaultInstanceForType() {
        return com.lvl6.proto.EventProto.ChatResponseProto.getDefaultInstance();
      }
      
      public com.lvl6.proto.EventProto.ChatResponseProto build() {
        com.lvl6.proto.EventProto.ChatResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.proto.EventProto.ChatResponseProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.proto.EventProto.ChatResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.proto.EventProto.ChatResponseProto buildPartial() {
        com.lvl6.proto.EventProto.ChatResponseProto result = new com.lvl6.proto.EventProto.ChatResponseProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.event_ = event_;
        if (recipientsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            recipients_ = java.util.Collections.unmodifiableList(recipients_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.recipients_ = recipients_;
        } else {
          result.recipients_ = recipientsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.proto.EventProto.ChatResponseProto) {
          return mergeFrom((com.lvl6.proto.EventProto.ChatResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.proto.EventProto.ChatResponseProto other) {
        if (other == com.lvl6.proto.EventProto.ChatResponseProto.getDefaultInstance()) return this;
        if (other.hasEvent()) {
          setEvent(other.getEvent());
        }
        if (recipientsBuilder_ == null) {
          if (!other.recipients_.isEmpty()) {
            if (recipients_.isEmpty()) {
              recipients_ = other.recipients_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRecipientsIsMutable();
              recipients_.addAll(other.recipients_);
            }
            onChanged();
          }
        } else {
          if (!other.recipients_.isEmpty()) {
            if (recipientsBuilder_.isEmpty()) {
              recipientsBuilder_.dispose();
              recipientsBuilder_ = null;
              recipients_ = other.recipients_;
              bitField0_ = (bitField0_ & ~0x00000002);
              recipientsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRecipientsFieldBuilder() : null;
            } else {
              recipientsBuilder_.addAllMessages(other.recipients_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              event_ = input.readInt32();
              break;
            }
            case 18: {
              com.lvl6.proto.InfoProto.UserProto.Builder subBuilder = com.lvl6.proto.InfoProto.UserProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRecipients(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 event = 1;
      private int event_ ;
      public boolean hasEvent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getEvent() {
        return event_;
      }
      public Builder setEvent(int value) {
        bitField0_ |= 0x00000001;
        event_ = value;
        onChanged();
        return this;
      }
      public Builder clearEvent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        event_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .com.lvl6.proto.UserProto recipients = 2;
      private java.util.List<com.lvl6.proto.InfoProto.UserProto> recipients_ =
        java.util.Collections.emptyList();
      private void ensureRecipientsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          recipients_ = new java.util.ArrayList<com.lvl6.proto.InfoProto.UserProto>(recipients_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.proto.InfoProto.UserProto, com.lvl6.proto.InfoProto.UserProto.Builder, com.lvl6.proto.InfoProto.UserProtoOrBuilder> recipientsBuilder_;
      
      public java.util.List<com.lvl6.proto.InfoProto.UserProto> getRecipientsList() {
        if (recipientsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(recipients_);
        } else {
          return recipientsBuilder_.getMessageList();
        }
      }
      public int getRecipientsCount() {
        if (recipientsBuilder_ == null) {
          return recipients_.size();
        } else {
          return recipientsBuilder_.getCount();
        }
      }
      public com.lvl6.proto.InfoProto.UserProto getRecipients(int index) {
        if (recipientsBuilder_ == null) {
          return recipients_.get(index);
        } else {
          return recipientsBuilder_.getMessage(index);
        }
      }
      public Builder setRecipients(
          int index, com.lvl6.proto.InfoProto.UserProto value) {
        if (recipientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecipientsIsMutable();
          recipients_.set(index, value);
          onChanged();
        } else {
          recipientsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setRecipients(
          int index, com.lvl6.proto.InfoProto.UserProto.Builder builderForValue) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.set(index, builderForValue.build());
          onChanged();
        } else {
          recipientsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addRecipients(com.lvl6.proto.InfoProto.UserProto value) {
        if (recipientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecipientsIsMutable();
          recipients_.add(value);
          onChanged();
        } else {
          recipientsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addRecipients(
          int index, com.lvl6.proto.InfoProto.UserProto value) {
        if (recipientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecipientsIsMutable();
          recipients_.add(index, value);
          onChanged();
        } else {
          recipientsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addRecipients(
          com.lvl6.proto.InfoProto.UserProto.Builder builderForValue) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.add(builderForValue.build());
          onChanged();
        } else {
          recipientsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addRecipients(
          int index, com.lvl6.proto.InfoProto.UserProto.Builder builderForValue) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.add(index, builderForValue.build());
          onChanged();
        } else {
          recipientsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllRecipients(
          java.lang.Iterable<? extends com.lvl6.proto.InfoProto.UserProto> values) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          super.addAll(values, recipients_);
          onChanged();
        } else {
          recipientsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearRecipients() {
        if (recipientsBuilder_ == null) {
          recipients_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          recipientsBuilder_.clear();
        }
        return this;
      }
      public Builder removeRecipients(int index) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.remove(index);
          onChanged();
        } else {
          recipientsBuilder_.remove(index);
        }
        return this;
      }
      public com.lvl6.proto.InfoProto.UserProto.Builder getRecipientsBuilder(
          int index) {
        return getRecipientsFieldBuilder().getBuilder(index);
      }
      public com.lvl6.proto.InfoProto.UserProtoOrBuilder getRecipientsOrBuilder(
          int index) {
        if (recipientsBuilder_ == null) {
          return recipients_.get(index);  } else {
          return recipientsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.lvl6.proto.InfoProto.UserProtoOrBuilder> 
           getRecipientsOrBuilderList() {
        if (recipientsBuilder_ != null) {
          return recipientsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(recipients_);
        }
      }
      public com.lvl6.proto.InfoProto.UserProto.Builder addRecipientsBuilder() {
        return getRecipientsFieldBuilder().addBuilder(
            com.lvl6.proto.InfoProto.UserProto.getDefaultInstance());
      }
      public com.lvl6.proto.InfoProto.UserProto.Builder addRecipientsBuilder(
          int index) {
        return getRecipientsFieldBuilder().addBuilder(
            index, com.lvl6.proto.InfoProto.UserProto.getDefaultInstance());
      }
      public java.util.List<com.lvl6.proto.InfoProto.UserProto.Builder> 
           getRecipientsBuilderList() {
        return getRecipientsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.proto.InfoProto.UserProto, com.lvl6.proto.InfoProto.UserProto.Builder, com.lvl6.proto.InfoProto.UserProtoOrBuilder> 
          getRecipientsFieldBuilder() {
        if (recipientsBuilder_ == null) {
          recipientsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.lvl6.proto.InfoProto.UserProto, com.lvl6.proto.InfoProto.UserProto.Builder, com.lvl6.proto.InfoProto.UserProtoOrBuilder>(
                  recipients_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          recipients_ = null;
        }
        return recipientsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.lvl6.proto.ChatResponseProto)
    }
    
    static {
      defaultInstance = new ChatResponseProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.lvl6.proto.ChatResponseProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lvl6_proto_ChatRequestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lvl6_proto_ChatRequestProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lvl6_proto_ChatResponseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lvl6_proto_ChatResponseProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Event.proto\022\016com.lvl6.proto\032\nUser.prot" +
      "o\"P\n\020ChatRequestProto\022\r\n\005event\030\001 \001(\005\022-\n\n" +
      "recipients\030\002 \003(\0132\031.com.lvl6.proto.UserPr" +
      "oto\"Q\n\021ChatResponseProto\022\r\n\005event\030\001 \001(\005\022" +
      "-\n\nrecipients\030\002 \003(\0132\031.com.lvl6.proto.Use" +
      "rProtoB\014B\nEventProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_lvl6_proto_ChatRequestProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_lvl6_proto_ChatRequestProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_lvl6_proto_ChatRequestProto_descriptor,
              new java.lang.String[] { "Event", "Recipients", },
              com.lvl6.proto.EventProto.ChatRequestProto.class,
              com.lvl6.proto.EventProto.ChatRequestProto.Builder.class);
          internal_static_com_lvl6_proto_ChatResponseProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_lvl6_proto_ChatResponseProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_lvl6_proto_ChatResponseProto_descriptor,
              new java.lang.String[] { "Event", "Recipients", },
              com.lvl6.proto.EventProto.ChatResponseProto.class,
              com.lvl6.proto.EventProto.ChatResponseProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lvl6.proto.InfoProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
