// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Info.proto

package com.lvl6.proto;

public final class InfoProto {
  private InfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MinimumUserProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 senderId = 1;
    boolean hasSenderId();
    int getSenderId();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
    
    // optional .com.lvl6.proto.MinimumUserProto.UserType userType = 3;
    boolean hasUserType();
    com.lvl6.proto.InfoProto.MinimumUserProto.UserType getUserType();
  }
  public static final class MinimumUserProto extends
      com.google.protobuf.GeneratedMessage
      implements MinimumUserProtoOrBuilder {
    // Use MinimumUserProto.newBuilder() to construct.
    private MinimumUserProto(Builder builder) {
      super(builder);
    }
    private MinimumUserProto(boolean noInit) {}
    
    private static final MinimumUserProto defaultInstance;
    public static MinimumUserProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public MinimumUserProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.proto.InfoProto.internal_static_com_lvl6_proto_MinimumUserProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.proto.InfoProto.internal_static_com_lvl6_proto_MinimumUserProto_fieldAccessorTable;
    }
    
    public enum UserType
        implements com.google.protobuf.ProtocolMessageEnum {
      GOOD_WARRIOR(0, 0),
      GOOD_ARCHER(1, 1),
      GOOD_MAGE(2, 2),
      BAD_WARRIOR(3, 3),
      BAD_ARCHER(4, 4),
      BAD_MAGE(5, 5),
      ;
      
      public static final int GOOD_WARRIOR_VALUE = 0;
      public static final int GOOD_ARCHER_VALUE = 1;
      public static final int GOOD_MAGE_VALUE = 2;
      public static final int BAD_WARRIOR_VALUE = 3;
      public static final int BAD_ARCHER_VALUE = 4;
      public static final int BAD_MAGE_VALUE = 5;
      
      
      public final int getNumber() { return value; }
      
      public static UserType valueOf(int value) {
        switch (value) {
          case 0: return GOOD_WARRIOR;
          case 1: return GOOD_ARCHER;
          case 2: return GOOD_MAGE;
          case 3: return BAD_WARRIOR;
          case 4: return BAD_ARCHER;
          case 5: return BAD_MAGE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<UserType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<UserType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<UserType>() {
              public UserType findValueByNumber(int number) {
                return UserType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.lvl6.proto.InfoProto.MinimumUserProto.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final UserType[] VALUES = {
        GOOD_WARRIOR, GOOD_ARCHER, GOOD_MAGE, BAD_WARRIOR, BAD_ARCHER, BAD_MAGE, 
      };
      
      public static UserType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private UserType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.lvl6.proto.MinimumUserProto.UserType)
    }
    
    private int bitField0_;
    // required int32 senderId = 1;
    public static final int SENDERID_FIELD_NUMBER = 1;
    private int senderId_;
    public boolean hasSenderId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getSenderId() {
      return senderId_;
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .com.lvl6.proto.MinimumUserProto.UserType userType = 3;
    public static final int USERTYPE_FIELD_NUMBER = 3;
    private com.lvl6.proto.InfoProto.MinimumUserProto.UserType userType_;
    public boolean hasUserType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.lvl6.proto.InfoProto.MinimumUserProto.UserType getUserType() {
      return userType_;
    }
    
    private void initFields() {
      senderId_ = 0;
      name_ = "";
      userType_ = com.lvl6.proto.InfoProto.MinimumUserProto.UserType.GOOD_WARRIOR;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSenderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, senderId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, userType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, senderId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, userType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.proto.InfoProto.MinimumUserProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.InfoProto.MinimumUserProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.InfoProto.MinimumUserProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.InfoProto.MinimumUserProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.InfoProto.MinimumUserProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.InfoProto.MinimumUserProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.InfoProto.MinimumUserProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.InfoProto.MinimumUserProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.InfoProto.MinimumUserProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.InfoProto.MinimumUserProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.proto.InfoProto.MinimumUserProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.proto.InfoProto.MinimumUserProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.proto.InfoProto.internal_static_com_lvl6_proto_MinimumUserProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.proto.InfoProto.internal_static_com_lvl6_proto_MinimumUserProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.proto.InfoProto.MinimumUserProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        senderId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        userType_ = com.lvl6.proto.InfoProto.MinimumUserProto.UserType.GOOD_WARRIOR;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.proto.InfoProto.MinimumUserProto.getDescriptor();
      }
      
      public com.lvl6.proto.InfoProto.MinimumUserProto getDefaultInstanceForType() {
        return com.lvl6.proto.InfoProto.MinimumUserProto.getDefaultInstance();
      }
      
      public com.lvl6.proto.InfoProto.MinimumUserProto build() {
        com.lvl6.proto.InfoProto.MinimumUserProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.proto.InfoProto.MinimumUserProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.proto.InfoProto.MinimumUserProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.proto.InfoProto.MinimumUserProto buildPartial() {
        com.lvl6.proto.InfoProto.MinimumUserProto result = new com.lvl6.proto.InfoProto.MinimumUserProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.senderId_ = senderId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userType_ = userType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.proto.InfoProto.MinimumUserProto) {
          return mergeFrom((com.lvl6.proto.InfoProto.MinimumUserProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.proto.InfoProto.MinimumUserProto other) {
        if (other == com.lvl6.proto.InfoProto.MinimumUserProto.getDefaultInstance()) return this;
        if (other.hasSenderId()) {
          setSenderId(other.getSenderId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasUserType()) {
          setUserType(other.getUserType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSenderId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              senderId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.lvl6.proto.InfoProto.MinimumUserProto.UserType value = com.lvl6.proto.InfoProto.MinimumUserProto.UserType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                userType_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 senderId = 1;
      private int senderId_ ;
      public boolean hasSenderId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getSenderId() {
        return senderId_;
      }
      public Builder setSenderId(int value) {
        bitField0_ |= 0x00000001;
        senderId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSenderId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        senderId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional .com.lvl6.proto.MinimumUserProto.UserType userType = 3;
      private com.lvl6.proto.InfoProto.MinimumUserProto.UserType userType_ = com.lvl6.proto.InfoProto.MinimumUserProto.UserType.GOOD_WARRIOR;
      public boolean hasUserType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.lvl6.proto.InfoProto.MinimumUserProto.UserType getUserType() {
        return userType_;
      }
      public Builder setUserType(com.lvl6.proto.InfoProto.MinimumUserProto.UserType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        userType_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userType_ = com.lvl6.proto.InfoProto.MinimumUserProto.UserType.GOOD_WARRIOR;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.lvl6.proto.MinimumUserProto)
    }
    
    static {
      defaultInstance = new MinimumUserProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.lvl6.proto.MinimumUserProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lvl6_proto_MinimumUserProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lvl6_proto_MinimumUserProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nInfo.proto\022\016com.lvl6.proto\"\334\001\n\020Minimum" +
      "UserProto\022\020\n\010senderId\030\001 \002(\005\022\014\n\004name\030\002 \001(" +
      "\t\022;\n\010userType\030\003 \001(\0162).com.lvl6.proto.Min" +
      "imumUserProto.UserType\"k\n\010UserType\022\020\n\014GO" +
      "OD_WARRIOR\020\000\022\017\n\013GOOD_ARCHER\020\001\022\r\n\tGOOD_MA" +
      "GE\020\002\022\017\n\013BAD_WARRIOR\020\003\022\016\n\nBAD_ARCHER\020\004\022\014\n" +
      "\010BAD_MAGE\020\005B\013B\tInfoProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_lvl6_proto_MinimumUserProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_lvl6_proto_MinimumUserProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_lvl6_proto_MinimumUserProto_descriptor,
              new java.lang.String[] { "SenderId", "Name", "UserType", },
              com.lvl6.proto.InfoProto.MinimumUserProto.class,
              com.lvl6.proto.InfoProto.MinimumUserProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
